version: 2
project_name: sing-box
builds:
  - id: main
    main: ./cmd/sing-box
    flags:
      - -v
      - -trimpath
    ldflags:
      - -X github.com/sagernet/sing-box/constant.Version={{ .Version }} -s -w -buildid=
    tags:
      - with_gvisor
      - with_quic
      - with_grpc
      - with_dhcp
      - with_wireguard
      - with_ech
      - with_utls
      - with_reality_server
      - with_acme
      - with_v2ray_api
      - with_clash_api
    env:
      - CGO_ENABLED=0
    targets:
      - linux_386
      - linux_amd64_v3
      - linux_arm64
      - linux_arm_7
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  - id: main
    format: tar.gz
    name_template: "{{ .ProjectName}}_{{ .Os}}_{{ .Arch}}_{{ .Version}}"
    files:
      - LICENSE
    builds_info:
      group: root
      owner: root
checksum:
  name_template: checksum.txt
snapshot:
  version_template: "{{ .Version }}"
release:
  github:
    owner: nolangilardi
    name: sing-box
  mode: replace