name: goreleaser

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true

permissions:
  contents: write
  # packages: write
  # issues: write
  # id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout sing-box
        uses: actions/checkout@v4
        with:
          repository: SagerNet/sing-box
          ref: ${{ github.event.inputs.version }}
          path: sing-box
          fetch-depth: 1
      - name: Override goreleaser config
        run: |
          cp .goreleaser.yaml sing-box/.goreleaser.yaml
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --snapshot
          workdir: sing-box
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
      - name: Upload release
        run: |
          gh release create ${{ github.event.inputs.version }} sing-box/dist/{*.tar.gz,checksum.txt} --title ${{ github.event.inputs.version }} --notes-file sing-box/dist/checksum.txt
